title: David Montgomery
remote_theme: just-the-docs/just-the-docs
description: A collection of various development projects and tools
url: https://dmontgomery40.github.io/Portfolio
favicon: "/assets/favicon.png"
aux_links:
  "View on GitHub":
    - "https://github.com/DMontgomery40"

color_scheme: dark

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Enable copy button on code blocks
enable_copy_code_button: true

# Enable anchors on headings
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2024 David Montgomery. Distributed under an MIT license."

# Collections
collections:
  projects:
    permalink: "/:collection/:path/"
    output: true

# Default values
defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      layout: page

callouts:
  note:
    title: Note
    color: blue

gh_edit_link: false

search_enabled: true

kramdown:
  parse_block_html: true

heading_anchors: true
