title: David Montgomery
remote_theme: just-the-docs/just-the-docs
description: A collection of various development projects and tools
url: https://dmontgomery40.github.io
baseurl: "/Portfolio"

# Theme settings
color_scheme: dark
search_enabled: true
heading_anchors: true

# Aux links
aux_links:
  "GitHub":
    - "https://github.com/DMontgomery40"

# Footer
footer_content: "Copyright &copy; 2025 David Montgomery."

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  projects:
    output: true
  articles:
    output: true
  homelab:
    output: true
  storytime:
    output: true
  resume:
    output: true

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "Projects"
      type: "pages"
    values:
      layout: "default"
      parent: "Projects"
  -
    scope:
      path: "articles"
      type: "pages"
    values:
      layout: "default"
      parent: "Articles"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
