title: David Montgomery
remote_theme: just-the-docs/just-the-docs
description: A collection of various development projects and tools
url: https://dmontgomery40.github.io/Portfolio/
baseurl: "/Portfolio"
favicon: "/Portfolio/assets/favicon.ico"

aux_links:
  "View on GitHub":
    - "https://github.com/DMontgomery40/Portfolio"

color_scheme: dark

# Enable search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

plugins:
  - jekyll-remote-include

# Enable copy button on code blocks
enable_copy_code_button: true

# Enable anchors on headings
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2025 David Montgomery."

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  articles:
    output: true
    permalink: /articles/:title/
  homelab:
    output: true
    permalink: /homelab/:title/
  storytime:
    output: true
    permalink: /storytime/:title/
  resume:
    output: true
    permalink: /resume/:title/

# Default values
defaults:
  -
    scope:
      path: "/Portfolio"
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: "/Portfolio"
      type: "articles"
    values:
      layout: "default"
  -
    scope:
      path: "/Portfolio"
      type: "homelab"
    values:
      layout: "default"
  -
    scope:
      path: "/Portfolio"
      type: "storytime"
    values:
      layout: "default"
  -
    scope:
      path: "/Portfolio"
      type: "resume"
    values:
      layout: "default"

callouts:
  note:
    title: Note
    color: white
  tip:
    title: Tip
    color: white
  warning:
    title: Warning
    color: white

gh_edit_link: false

kramdown:
  parse_block_html: true

# Navigation structure
nav_order: 1
nav_sort: case_sensitive

# External navigation
nav_external_links:
  - title: LinkedIn
    url: https://linkedin.com/in/dmontgomery40
  - title: Medium
    url: https://medium.com/@dmontg
