title: David Montgomery
remote_theme: just-the-docs/just-the-docs
description: A collection of various development projects and tools
url: https://dmontgomery40.github.io/Portfolio

aux_links:
  "View on GitHub":
    - "https://github.com/DMontgomery40"

color_scheme: dark

callouts:
  note:
    title: Note
    color: blue

gh_edit_link: false

search_enabled: true

kramdown:
  parse_block_html: true

heading_anchors: true
